---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 93.77.183.243
      ansible_user: almalinux

vector:
  hosts:
    vector-01:
      ansible_host: 93.77.178.4
      ansible_user: ubuntu

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.1.254
      ansible_user: ubuntu
